# -*- coding: utf-8 -*-
"""Business configuration, ECS matrix mapping, and row specifications for Section B."""

from typing import Dict, Any, List, Optional
from .enums import (
    CreditNeedId, ProposalType, IssuanceStructure, LoanTermType,
    TenorClassification, ProductTypeLC, ProductTypeDiscount
)

# 1. Danh mục 8 Nhu cầu tín dụng Mục 2
CREDIT_NEEDS_CATALOG = [
    {
        "id": CreditNeedId.NEED_2_1.value,
        "code": "2.1",
        "title": "2.1 – Cho vay VLĐ theo hạn mức",
        "heading_pattern": "2.1 Cho vay VLĐ",
        "default_ecs": "ECS1101",
        "table_index": 1,
        "group": "A",
    },
    {
        "id": CreditNeedId.NEED_2_2.value,
        "code": "2.2",
        "title": "2.2 – Cho vay VLĐ hạn mức trên 12 tháng",
        "heading_pattern": "2.2 Cho vay VLĐ hạn mức trên",
        "default_ecs": "ECS1101",
        "table_index": 2,
        "group": "C",
    },
    {
        "id": CreditNeedId.NEED_2_3.value,
        "code": "2.3",
        "title": "2.3 – Vay ngắn hạn từng lần",
        "heading_pattern": "2.3 Vay ngắn hạn",
        "default_ecs": "ECS1109",
        "table_index": 3,
        "group": "D",
    },
    {
        "id": CreditNeedId.NEED_2_4.value,
        "code": "2.4",
        "title": "2.4 – Vay trung/dài hạn",
        "heading_pattern": "2.4 Vay trung/dài hạn",
        "default_ecs": "ECS2100/ECS2400/ECS3100/ECS3400",
        "table_index": 4,
        "group": "D",
    },
    {
        "id": CreditNeedId.NEED_2_5.value,
        "code": "2.5",
        "title": "2.5 – Hạn mức/từng lần phát hành L/C/Nhờ thu",
        "heading_pattern": "2.5 Hạn mức/ từng lần phát hành L/C",
        "default_ecs": "ECS1308/1309/....",
        "table_index": 5,
        "group": "A",  # can also map to C or D depending on tenor/structure
    },
    {
        "id": CreditNeedId.NEED_2_6.value,
        "code": "2.6",
        "title": "2.6 – Hạn mức/từng lần Bảo lãnh",
        "heading_pattern": "2.6 Hạn mức/từng lần Bảo lãnh",
        "default_ecs": "ECS1200/2200/3200",
        "table_index": 6,
        "group": "A",  # can also map to C or D
    },
    {
        "id": CreditNeedId.NEED_2_7.value,
        "code": "2.7",
        "title": "2.7 – Hạn mức/từng lần chiết khấu BCT/Bao thanh toán",
        "heading_pattern": "2.7 Hạn mức/ từng lần chiết khấu",
        "default_ecs": "ECS1102/...",
        "table_index": 7,
        "group": "A",  # can also map to C
    },
    {
        "id": CreditNeedId.NEED_2_8.value,
        "code": "2.8",
        "title": "2.8 – Hạn mức rủi ro tín dụng đối tác",
        "heading_pattern": "2.8 Hạn mức rủi ro",
        "default_ecs": "ECS9000/ECS9100/9200/9300",
        "table_index": 8,
        "group": "B",  # can also map to D
    },
]

# 2. Đặc tả các dòng của Bảng Mục 1 (Table 0) - Định vị ổn định theo Label & Mã ECS
SECTION_1_ROWS_SPEC = [
    # Header: row 0 is table column headers ("Cụ thể", "Mã hạn mức", etc.)
    # Group A
    {
        "row_id": "A_GROUP",
        "group": "A",
        "label_pattern": "A. Tín dụng hạn mức ngắn hạn",
        "ecs_code": "ECS1000",
        "is_group_header": True,
        "is_subtotal": False,
        "has_checkbox": True,
    },
    {
        "row_id": "A_ECS1100",
        "group": "A",
        "label_pattern": "Cho vay ngắn hạn theo hạn mức",
        "ecs_code": "ECS1100",
        "need_id": CreditNeedId.NEED_2_1.value,
        "is_facility": True,
        "has_checkbox": True,
    },
    {
        "row_id": "A_ECS1200",
        "group": "A",
        "label_pattern": "Bảo lãnh",
        "ecs_code": "ECS1200",
        "need_id": CreditNeedId.NEED_2_6.value,
        "condition_tenor": [TenorClassification.NGAN_HAN.value],
        "condition_structure": [IssuanceStructure.HAN_MUC.value],
        "is_facility": True,
        "has_checkbox": True,
    },
    {
        "row_id": "A_ECS1300",
        "group": "A",
        "label_pattern": "Phát hành L/C",
        "ecs_code": "ECS1300",
        "need_id": CreditNeedId.NEED_2_5.value,
        "condition_tenor": [TenorClassification.NGAN_HAN.value],
        "condition_structure": [IssuanceStructure.HAN_MUC.value],
        "is_facility": True,
        "has_checkbox": True,
    },
    {
        "row_id": "A_ECS1400",
        "group": "A",
        "label_pattern": "Chiết khấu hoàn hảo",
        "ecs_code": "ECS1400",
        "need_id": CreditNeedId.NEED_2_7.value,
        "condition_structure": [IssuanceStructure.HAN_MUC.value],
        "is_facility": True,
        "has_checkbox": True,
    },
    # Group B
    {
        "row_id": "B_GROUP",
        "group": "B",
        "label_pattern": "B. Rủi ro tín dụng đối tác",
        "ecs_code": "",
        "is_group_header": True,
        "is_subtotal": False,
        "has_checkbox": False,
    },
    {
        "row_id": "B_ECS9100",
        "group": "B",
        "label_pattern": "Rủi ro tín dụng đối tác",
        "ecs_code": "ECS9100",
        "need_id": CreditNeedId.NEED_2_8.value,
        "is_facility": True,
        "has_checkbox": True,
    },
    # Subtotal Group A + B
    {
        "row_id": "TOTAL_HM",
        "group": "SUBTOTAL_AB",
        "label_pattern": "Tổng tín dụng hạn mức",
        "ecs_code": "",
        "is_group_header": False,
        "is_subtotal": True,
        "has_checkbox": False,
    },
    # Group C
    {
        "row_id": "C_GROUP",
        "group": "C",
        "label_pattern": "C. Hạn mức tài trợ VLĐ trên 12 tháng",
        "ecs_code": "ECS1000",
        "is_group_header": True,
        "is_subtotal": False,
        "has_checkbox": False,
    },
    {
        "row_id": "C_ECS1100",
        "group": "C",
        "label_pattern": "Cho vay VLĐ",
        "ecs_code": "ECS1100",
        "need_id": CreditNeedId.NEED_2_2.value,
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "C_ECS1200",
        "group": "C",
        "label_pattern": "Bảo lãnh",
        "ecs_code": "ECS1200",
        "need_id": CreditNeedId.NEED_2_6.value,
        "condition_tenor": [TenorClassification.TREN_12T.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "C_ECS1300",
        "group": "C",
        "label_pattern": "Phát hành L/C",
        "ecs_code": "ECS1300",
        "need_id": CreditNeedId.NEED_2_5.value,
        "condition_tenor": [TenorClassification.TREN_12T.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "C_ECS1400",
        "group": "C",
        "label_pattern": "Chiết khấu hoàn hảo",
        "ecs_code": "ECS1400",
        "need_id": CreditNeedId.NEED_2_7.value,
        "condition_structure": [IssuanceStructure.HAN_MUC.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    # Group D
    {
        "row_id": "D_GROUP",
        "group": "D",
        "label_pattern": "D.Tín dụng từng lần",
        "ecs_code": "",
        "is_group_header": True,
        "is_subtotal": False,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS1109",
        "group": "D",
        "label_pattern": "Vay ngắn hạn cấp từng lần",
        "ecs_code": "ECS1109",
        "need_id": CreditNeedId.NEED_2_3.value,
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS2100",
        "group": "D",
        "label_pattern": "Vay trung hạn",
        "ecs_code": "ECS2100",
        "need_id": CreditNeedId.NEED_2_4.value,
        "condition_loan_type": [LoanTermType.TRUNG_HAN.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS2200",
        "group": "D",
        "label_pattern": "Bảo lãnh trung hạn",
        "ecs_code": "ECS2200",
        "need_id": CreditNeedId.NEED_2_6.value,
        "condition_tenor": [TenorClassification.TRUNG_HAN.value],
        "condition_structure": [IssuanceStructure.TUNG_LAN.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS2300",
        "group": "D",
        "label_pattern": "Phát hành L/C trung hạn",
        "ecs_code": "ECS2300",
        "need_id": CreditNeedId.NEED_2_5.value,
        "condition_tenor": [TenorClassification.TRUNG_HAN.value],
        "condition_structure": [IssuanceStructure.TUNG_LAN.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS3100",
        "group": "D",
        "label_pattern": "Vay dài hạn",
        "ecs_code": "ECS3100",
        "need_id": CreditNeedId.NEED_2_4.value,
        "condition_loan_type": [LoanTermType.DAI_HAN.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS3200",
        "group": "D",
        "label_pattern": "Bảo lãnh dài hạn",
        "ecs_code": "ECS3200",
        "need_id": CreditNeedId.NEED_2_6.value,
        "condition_tenor": [TenorClassification.DAI_HAN.value],
        "condition_structure": [IssuanceStructure.TUNG_LAN.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS3300",
        "group": "D",
        "label_pattern": "Phát hành L/C dài hạn",
        "ecs_code": "ECS3300",
        "need_id": CreditNeedId.NEED_2_5.value,
        "condition_tenor": [TenorClassification.DAI_HAN.value],
        "condition_structure": [IssuanceStructure.TUNG_LAN.value],
        "is_facility": True,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS7000",
        "group": "D",
        "label_pattern": "Đầu tư (mua) TPDN",
        "ecs_code": "ECS7000",
        "is_facility": False,  # out of current scope
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS9200",
        "group": "D",
        "label_pattern": "Rủi ro tín dụng đối tác NH",
        "ecs_code": "ECS9200",
        "need_id": CreditNeedId.NEED_2_8.value,
        "is_facility": False,
        "has_checkbox": False,
    },
    {
        "row_id": "D_ECS9300",
        "group": "D",
        "label_pattern": "Rủi ro tín dụng đối tác TDH",
        "ecs_code": "ECS9300",
        "need_id": CreditNeedId.NEED_2_8.value,
        "is_facility": False,
        "has_checkbox": False,
    },
    # Subtotal Group D
    {
        "row_id": "TOTAL_TUNG_LAN",
        "group": "SUBTOTAL_D",
        "label_pattern": "Tổng tín dụng từng lần",
        "ecs_code": "",
        "is_group_header": False,
        "is_subtotal": True,
        "has_checkbox": False,
    },
    # Group E
    {
        "row_id": "E_GROUP",
        "group": "E",
        "label_pattern": "E. Khác",
        "ecs_code": "ECS...",
        "is_group_header": True,
        "is_subtotal": False,
        "has_checkbox": False,
    },
    {
        "row_id": "E_OTHER",
        "group": "E",
        "label_pattern": "....",
        "ecs_code": "",
        "is_facility": False,
        "has_checkbox": False,
    },
]

# 3. Master Dropdown Options
EFFECTIVE_DATE_MASTER_OPTIONS = [
    "Kể từ ngày ký Hợp đồng tín dụng",
    "Kể từ ngày phê duyệt khoản vay",
    "Ngày cụ thể",
    "Khác",
]

DISBURSEMENT_MASTER_OPTIONS = [
    "Chuyển khoản trực tiếp vào tài khoản bên thụ hưởng",
    "Chuyển khoản hoặc tiền mặt theo quy định MSB",
    "Tiền mặt",
    "Khác",
]

GUARANTEE_TYPE_OPTIONS = [
    "Bảo lãnh dự thầu",
    "Bảo lãnh thực hiện hợp đồng",
    "Bảo lãnh tạm ứng",
    "Bảo lãnh thanh toán",
    "Bảo lãnh bảo hành",
    "Bảo lãnh thuế, hải quan",
    "Hỗn hợp các loại bảo lãnh",
]
