# -*- coding: utf-8 -*-
"""Canonical Case Data Contract Validator & Compatibility Adapters.

Module: msb_eb_copilot.src.canonical_validator
Purpose:
- Enforces ONE CANONICAL CASE DATA CONTRACT for Sections A-E.
- Distinguishes BLOCKING STRUCTURAL ERRORS from DOWNSTREAM READINESS WARNINGS (supports partial cases).
- Preserves input non-mutation.
- Enforces strict data ownership (SOURCE_FACT, RM_INPUT, DERIVED_PYTHON, AI_NARRATIVE, SYSTEM_METADATA).
- Provides one-way compatibility adapters for legacy consumers.
"""

from __future__ import annotations
import copy
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union


class FieldOwner(str, Enum):
    """Authoritative field ownership classification."""
    SOURCE_FACT = "SOURCE_FACT"         # Document extracted facts (GreenNode eligible)
    RM_INPUT = "RM_INPUT"               # RM intent & discretionary decisions (GreenNode CANNOT decide)
    DERIVED_PYTHON = "DERIVED_PYTHON"   # Deterministically calculated by Python (GreenNode CANNOT overwrite)
    AI_NARRATIVE = "AI_NARRATIVE"       # Grounded synthesis generated by GreenNode with evidence
    SYSTEM_METADATA = "SYSTEM_METADATA" # Routing / identification metadata


@dataclass
class ContractValidationReport:
    """Validation report distinguishing blocking structural errors from readiness warnings."""
    is_valid: bool = True
    blocking_errors: List[str] = field(default_factory=list)
    readiness_warnings: List[str] = field(default_factory=list)
    legacy_compatibility_warnings: List[str] = field(default_factory=list)

    @property
    def has_warnings(self) -> bool:
        return len(self.readiness_warnings) > 0 or len(self.legacy_compatibility_warnings) > 0

    def summary(self) -> str:
        status = "PASSED" if self.is_valid else "FAILED"
        msg = f"Contract Validation Status: {status}\n"
        if self.blocking_errors:
            msg += f"  Blocking Errors ({len(self.blocking_errors)}):\n"
            for err in self.blocking_errors:
                msg += f"    - [ERROR] {err}\n"
        if self.readiness_warnings:
            msg += f"  Downstream Readiness Warnings ({len(self.readiness_warnings)}):\n"
            for w in self.readiness_warnings:
                msg += f"    - [WARN-READINESS] {w}\n"
        if self.legacy_compatibility_warnings:
            msg += f"  Legacy Compatibility Warnings ({len(self.legacy_compatibility_warnings)}):\n"
            for w in self.legacy_compatibility_warnings:
                msg += f"    - [WARN-COMPAT] {w}\n"
        if not self.blocking_errors and not self.has_warnings:
            msg += "  All canonical structures and types conform cleanly.\n"
        return msg


def validate_case_data_contract(case_data: Any) -> ContractValidationReport:
    """Validate case_data against the Canonical Case Schema.

    Non-breaking, non-mutating.
    Supports partial cases: Missing optional or downstream facts generate
    readiness warnings rather than blocking errors.
    """
    report = ContractValidationReport()

    # 1. Structural check: root must be a dict
    if not isinstance(case_data, dict):
        report.is_valid = False
        report.blocking_errors.append(f"Root case_data must be a dict, got {type(case_data).__name__}.")
        return report

    # 2. Required top-level container checks
    required_containers = [
        "customer",
        "rm_metadata",
        "section_b",
        "section_c",
        "section_d",
        "section_e",
    ]
    for container in required_containers:
        if container not in case_data:
            report.is_valid = False
            report.blocking_errors.append(f"Missing required top-level section container: '{container}'.")
        elif not isinstance(case_data[container], dict):
            report.is_valid = False
            report.blocking_errors.append(
                f"Top-level container '{container}' must be a dict, got {type(case_data[container]).__name__}."
            )

    # If top-level structure is broken, halt further deep inspection
    if not report.is_valid:
        return report

    cust = case_data["customer"]
    rm = case_data["rm_metadata"]
    b = case_data["section_b"]
    c = case_data["section_c"]
    d = case_data["section_d"]
    e = case_data["section_e"]

    # -----------------------------------------------------------------
    # 3. SECTION A / CUSTOMER CONTRACT
    # -----------------------------------------------------------------
    # tax_code: strictly str if present
    if "tax_code" in cust and cust["tax_code"] is not None:
        if not isinstance(cust["tax_code"], str):
            report.is_valid = False
            report.blocking_errors.append(
                f"customer.tax_code must be a string preserving leading zeros, got {type(cust['tax_code']).__name__}."
            )
        elif not cust["tax_code"].strip():
            report.readiness_warnings.append("customer.tax_code is empty string.")

    # charter_capital: numeric >= 0 if present (unit: triệu VND)
    if "charter_capital" in cust and cust["charter_capital"] is not None:
        if not isinstance(cust["charter_capital"], (int, float)):
            report.is_valid = False
            report.blocking_errors.append(
                f"customer.charter_capital must be numeric (triệu VND), got {type(cust['charter_capital']).__name__}."
            )
        elif cust["charter_capital"] < 0:
            report.is_valid = False
            report.blocking_errors.append(
                f"customer.charter_capital cannot be negative, got {cust['charter_capital']}."
            )

    # Legacy duplicate check: revenue_2025 in customer
    if "revenue_2025" in cust and cust["revenue_2025"] is not None:
        report.legacy_compatibility_warnings.append(
            "customer.revenue_2025 is a legacy duplicate. Canonical path is section_d.net_revenue[-1]."
        )

    # Downstream readiness for customer
    if cust.get("name") is None:
        report.readiness_warnings.append("customer.name is not populated (required for proposal generation).")
    if cust.get("cif") is None:
        report.readiness_warnings.append("customer.cif is not populated (required for final Section A submission).")

    # -----------------------------------------------------------------
    # 4. SECTION B / CREDIT REQUEST CONTRACT
    # -----------------------------------------------------------------
    # limits: numeric >= 0 if present (unit: triệu VND)
    for limit_field in ["total_limit", "loan_limit", "guarantee_limit"]:
        if limit_field in b and b[limit_field] is not None:
            if not isinstance(b[limit_field], (int, float)):
                report.is_valid = False
                report.blocking_errors.append(
                    f"section_b.{limit_field} must be numeric (triệu VND), got {type(b[limit_field]).__name__}."
                )
            elif b[limit_field] < 0:
                report.is_valid = False
                report.blocking_errors.append(
                    f"section_b.{limit_field} cannot be negative, got {b[limit_field]}."
                )

    if b.get("selected_needs") is not None and not isinstance(b.get("selected_needs"), (list, tuple)):
        report.is_valid = False
        report.blocking_errors.append(
            f"section_b.selected_needs must be a list of product IDs, got {type(b['selected_needs']).__name__}."
        )

    # Readiness
    if b.get("total_limit") is None:
        report.readiness_warnings.append("section_b.total_limit is not set (required for Section B engine).")

    # -----------------------------------------------------------------
    # 5. SECTION C / BUSINESS PROFILE CONTRACT
    # -----------------------------------------------------------------
    for list_key in ["shareholders", "management", "products", "suppliers", "customers"]:
        if list_key in c and c[list_key] is not None:
            if not isinstance(c[list_key], list):
                report.is_valid = False
                report.blocking_errors.append(
                    f"section_c.{list_key} must be a list of structured records, got {type(c[list_key]).__name__}."
                )

    # -----------------------------------------------------------------
    # 6. SECTION D / FINANCIAL CONTRACT
    # -----------------------------------------------------------------
    years = d.get("years")
    if years is not None:
        if not isinstance(years, list):
            report.is_valid = False
            report.blocking_errors.append(f"section_d.years must be a list of year strings, got {type(years).__name__}.")
        else:
            num_years = len(years)
            financial_arrays = [
                "net_revenue",
                "cogs",
                "gross_profit",
                "net_profit_after_tax",
                "current_assets",
                "cash",
                "receivables",
                "inventories",
                "total_assets",
                "short_term_debt",
                "equity",
            ]
            for arr_key in financial_arrays:
                if arr_key in d and d[arr_key] is not None:
                    arr_val = d[arr_key]
                    if not isinstance(arr_val, list):
                        report.is_valid = False
                        report.blocking_errors.append(
                            f"section_d.{arr_key} must be a list of numeric values, got {type(arr_val).__name__}."
                        )
                    elif len(arr_val) != num_years:
                        report.is_valid = False
                        report.blocking_errors.append(
                            f"section_d.{arr_key} length ({len(arr_val)}) does not match section_d.years length ({num_years})."
                        )
    else:
        report.readiness_warnings.append("section_d.years is not populated (partial case: financial analysis pending).")

    # Readiness check for MB09
    if not d.get("net_revenue"):
        report.readiness_warnings.append("section_d.net_revenue is empty (required for MB09 working capital engine).")

    # -----------------------------------------------------------------
    # 7. SECTION E / CIC CONTRACT
    # -----------------------------------------------------------------
    if "msb_outstanding" in e and e["msb_outstanding"] is not None:
        if not isinstance(e["msb_outstanding"], (int, float)):
            report.is_valid = False
            report.blocking_errors.append(
                f"section_e.msb_outstanding must be numeric (triệu VND), got {type(e['msb_outstanding']).__name__}."
            )
        elif e["msb_outstanding"] < 0:
            report.is_valid = False
            report.blocking_errors.append(
                f"section_e.msb_outstanding cannot be negative, got {e['msb_outstanding']}."
            )

    if "relations" in e and e["relations"] is not None:
        if not isinstance(e["relations"], list):
            report.is_valid = False
            report.blocking_errors.append(
                f"section_e.relations must be a list of credit institution records, got {type(e['relations']).__name__}."
            )

    return report


class CanonicalAdapter:
    """One-way compatibility adapter from Canonical case_data to legacy consumers.
    
    Rules:
    - section_d.net_revenue is the ONLY canonical revenue series.
    - customer.revenue_2025 is legacy read-only fallback; never writable by GreenNode or RM.
    - charter_capital != shareholders[*].val (Total registered capital vs individual shareholder equity).
    - customer.legal_rep_name != section_c.management[0].name (Distinct concepts).
    - customer.parent_group != section_c.parent_company_or_owner (Distinct concepts).
    """

    @staticmethod
    def get_latest_revenue(case_data: Dict[str, Any], warnings_collector: Optional[List[str]] = None) -> Optional[float]:
        """Resolve latest revenue authoritatively from section_d, with legacy fallback.
        
        If falling back to customer.revenue_2025, appends a compatibility warning.
        """
        sec_d = case_data.get("section_d", {})
        net_rev = sec_d.get("net_revenue")
        if isinstance(net_rev, list) and len(net_rev) > 0 and net_rev[-1] is not None:
            return float(net_rev[-1])

        cust = case_data.get("customer", {})
        legacy_rev = cust.get("revenue_2025")
        if legacy_rev is not None:
            if warnings_collector is not None:
                warnings_collector.append(
                    "Resolved revenue via legacy fallback customer.revenue_2025. Future extraction must write to section_d.net_revenue."
                )
            return float(legacy_rev)

        return None

    @staticmethod
    def get_charter_capital(case_data: Dict[str, Any]) -> Optional[float]:
        """Resolve canonical company-wide registered charter capital in triệu VND."""
        cust = case_data.get("customer", {})
        val = cust.get("charter_capital")
        return float(val) if val is not None else None

    @staticmethod
    def reconcile_shareholders_capital(case_data: Dict[str, Any]) -> Tuple[Optional[float], Optional[float], bool]:
        """Reconcile company total charter capital against sum of individual shareholder values.
        
        Returns:
            (charter_capital, sum_shareholder_vals, is_reconciled)
        """
        charter = CanonicalAdapter.get_charter_capital(case_data)
        shareholders = case_data.get("section_c", {}).get("shareholders", [])
        if not shareholders:
            return charter, None, False

        sum_vals = 0.0
        for s in shareholders:
            val = s.get("val") or s.get("contributed_capital_million_vnd") or 0.0
            sum_vals += float(val)

        if charter is None:
            return None, sum_vals, False

        # Tolerance 5 triệu VND for public rounding differences
        is_reconciled = abs(charter - sum_vals) <= 5.0
        return charter, sum_vals, is_reconciled

    @staticmethod
    def to_legacy_customer(case_data: Dict[str, Any]) -> Dict[str, Any]:
        """Produce a read-only customer dictionary ensuring legacy consumers find revenue_2025."""
        cust = copy.deepcopy(case_data.get("customer", {}))
        if cust.get("revenue_2025") is None:
            latest_rev = CanonicalAdapter.get_latest_revenue(case_data)
            if latest_rev is not None:
                cust["revenue_2025"] = latest_rev
        return cust
