"""Enums for document classification and modality detection."""

from enum import Enum


class DocumentClass(str, Enum):
    """Semantic document classes in the MSB Credit Proposal workflow."""

    ENTERPRISE_REGISTRATION = "ENTERPRISE_REGISTRATION"
    COMPANY_CHARTER = "COMPANY_CHARTER"
    AUDITED_FINANCIAL_STATEMENTS = "AUDITED_FINANCIAL_STATEMENTS"
    INTERNAL_FINANCIAL_STATEMENTS = "INTERNAL_FINANCIAL_STATEMENTS"
    FINANCIAL_WORKBOOK_MB09 = "FINANCIAL_WORKBOOK_MB09"
    FINANCIAL_WORKBOOK_MB06 = "FINANCIAL_WORKBOOK_MB06"
    SHAREHOLDER_RELATED_PARTIES = "SHAREHOLDER_RELATED_PARTIES"
    ANNUAL_REPORT = "ANNUAL_REPORT"
    CREDIT_INSTITUTION_REPORT_CIC = "CREDIT_INSTITUTION_REPORT_CIC"
    CREDIT_PROPOSAL_DOCX = "CREDIT_PROPOSAL_DOCX"
    GENERAL_BUSINESS_DOCUMENT = "GENERAL_BUSINESS_DOCUMENT"
    UNKNOWN = "UNKNOWN"


class Modality(str, Enum):
    """Physical format and processing route for a document."""

    TEXT_PDF = "TEXT_PDF"
    SCANNED_IMAGE_PDF = "SCANNED_IMAGE_PDF"
    SPREADSHEET = "SPREADSHEET"
    WORD_DOCUMENT = "WORD_DOCUMENT"
    IMAGE = "IMAGE"
    UNKNOWN = "UNKNOWN"
